### ISSUE TITLE
environment_ql Python 3 - not working

### ISSUE THREAD

**Issue by Rognva1dr** [qLab/qLib#1265]
``Hi I like to use the environment_ql - but its not reading my site_environment.py any more,
and has the following error:

[210324 14:05.48 Env.qL] ERROR: running env script '/mnt/FRAMESTORE/job/dev/dev/pipeline/site_environment.py'
[210324 14:05.48 Env.qL]  | Traceback (most recent call last):
[210324 14:05.48 Env.qL]  |   File "qLib::Object/environment_ql::1, PythonModule", line 184, in scan_env
[210324 14:05.48 Env.qL]  | TypeError: exec() arg 1 must be a string, bytes or code object
[210324 14:05.48 Env.qL]  | 
Error running event handler:
Traceback (most recent call last):
  File "qLib::Object/environment_ql::1, opdef:/qLib::Object/environment_ql::1?OnCreated, node /obj/environment_ql1", line 1, in <module>
  File "qLib::Object/environment_ql::1, PythonModule", line 570, in rescan
hou.NodeError: Error generated by Python node.
Error(s) while rescanning:
FAILED: /mnt/FRAMESTORE/job/dev/dev/pipeline/site_environment.py
Traceback (most recent call last):
  File "qLib::Object/environment_ql::1, PythonModule", line 184, in scan_env
TypeError: exec() arg 1 must be a string, bytes or code object

 Giff of houdini attached

Thank you
![environment_ql_2021-03-24_14-07](https://user-images.githubusercontent.com/56594603/112324397-ab3a8480-8caa-11eb-83f9-e37725644256.gif)

Neil

**Comment by Rognva1dr** [comment]
site environment as
[site_environment.txt](https://github.com/qLab/qLib/files/6197882/site_environment.txt)
  .txt file so you can see that ( .py wont upload )

**Comment by johnnyquest** [comment]
hi @Rognva1dr -- interesting, when I try your site_environment.py with the node the error I get is --

```
Traceback (most recent call last):
  File "opdef:/qLib::Object/environment_ql::1?OnLoaded", line 1, in <module>
  File "opdef:/qLib::Object/environment_ql::1?PythonModule", line 579, in rescanOnLoaded
  File "opdef:/qLib::Object/environment_ql::1?PythonModule", line 570, in rescan
NodeError: Error generated by Python node.
Error(s) while rescanning:
FAILED: /home/tusi/Downloads/site_environment.py
Traceback (most recent call last):
  File "opdef:/qLib::Object/environment_ql::1?PythonModule", line 184, in scan_env
  File "/home/.../Downloads/site_environment.py", line 31, in <module>
    SHOTBASE = WORK.split("/")[4]
IndexError: list index out of range
```
...and if I remove the second half of your script (starting from that line) it works. So at least on my computer it's working?

Also be aware that in python 3 print() is a statement, so your last few lines might cause issues.

I'm not sure where this whole " TypeError: exec() arg 1 must be a string, bytes or code object" thing is coming from, but I'd be happy to look into a fix if I could reproduce it.

**Comment by johnnyquest** [comment]
Ok I'll push an update soon, I think it was a bug that was always there, but was tolerated under 2.x

**Comment by johnnyquest** [comment]
@Rognva1dr ok, update is out, v0.2.196, I'm closing this ticket but please reopen + mention me here if you're still running into issues, and I'll take another look. Cheers

**Comment by Rognva1dr** [comment]
Thank you ! - your fix worked -> ( and changing the print() statement in my site_environment.py ) 

Thanks for your help!

qLib Rocks!

Neil

**Comment by johnnyquest** [comment]
Awesome, thanks for letting me know. Cheers
