### ISSUE TITLE
ERROR - An HDA inside of the BASE Otls that causes "ValueError: not enough values to unpack (expected 2, got 1)"

### ISSUE THREAD

**Issue by dancristino** [qLab/qLib#1285]
# The newest DEV version of qLib is causing this error to occur:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\PROGRA~1\SIDEEF~1\Houdini 18.5.672\python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:/PROGRA~1/SIDEEF~1/Houdini 18.5.672/houdini/python3.7libs\houdinihelp\api.py", line 589, in run
    indexer.update_with(w, pages, overlay=True)
  File "C:/PROGRA~1/SIDEEF~1/Houdini 18.5.672/houdini/python3.7libs\bookish\search.py", line 486, in update_with
    writer, pages, update_paths, needs_delete=changed
  File "C:/PROGRA~1/SIDEEF~1/Houdini 18.5.672/houdini/python3.7libs\bookish\search.py", line 516, in index_paths_with
    for doc in self.documents(pages, path):
  File "C:/PROGRA~1/SIDEEF~1/Houdini 18.5.672/houdini/python3.7libs\bookish\search.py", line 417, in documents
    jsondata = pages.json(path, postprocess=False)
  File "C:/PROGRA~1/SIDEEF~1/Houdini 18.5.672/houdini/python3.7libs\bookish\wiki\wikipages.py", line 607, in json
    self._pre_pipeline.apply(jsondata, wcontext)
  File "C:/PROGRA~1/SIDEEF~1/Houdini 18.5.672/houdini/python3.7libs\bookish\wiki\pipeline.py", line 118, in apply
    v.apply(block, context)
  File "C:/PROGRA~1/SIDEEF~1/Houdini 18.5.672/houdini/python3.7libs\houdinihelp\hpages.py", line 324, in apply
    self.apply(subblock, context)
  File "C:/PROGRA~1/SIDEEF~1/Houdini 18.5.672/houdini/python3.7libs\houdinihelp\hpages.py", line 320, in apply
    self.text(block["text"], context)
  File "C:/PROGRA~1/SIDEEF~1/Houdini 18.5.672/houdini/python3.7libs\houdinihelp\hpages.py", line 340, in text
    value = self._parse_opdef(context["path"], value)
  File "C:/PROGRA~1/SIDEEF~1/Houdini 18.5.672/houdini/python3.7libs\houdinihelp\hpages.py", line 284, in _parse_opdef
    table, nodetype = nodetype.split("/")
ValueError: not enough values to unpack (expected 2, got 1)

```

The error only disappears if the the variable "$QOTL/base" is removed from the "HOUDINI_OTLSCAN_PATH".

#### FOUND THEM!
The following OTLs are causing the error:

- camera_frustrum_ql_SOP
- camera_plane_ql_2_SOP
- camera_plane_ql_SOP

**Comment by ReimuSG** [comment]
I checked the HDA file in qLib, and then found that camera_plane_ql caused this error because of the reason for the node's help documentation included a illegal character, after I removed it, this error was solved.

The content of the problematic line is:
[Image:opdef:Sop/qLib::camera_plane_ql::1?camera_plane_ql_sop_main.png]

change into:
[Image:opdef:Sop/qLib::camera_plane_ql::1camera_plane_ql_sop_main.png]

Of course, even if this problem is not repaired, it will not affect the use of this node, it will only lead to this node. :D

#1286

**Comment by johnnyquest** [comment]
Thanks guys, I'll look into this

**Comment by johnnyquest** [comment]
v0.2.199 should fix this, so I'm closing this ticket too. thanks for the feedback! cheers
