### ISSUE TITLE
Houdini help can be sucky ATM?

### ISSUE THREAD

**Issue by johnnyquest** [qLab/qLib#371]
WTF?
- Houdini has problems displaying help pages of assets (?)
- ~~(here at Luma sometimes even tooltips give python errors, but that's an internal pythonpath-screwup to be sorted out)~~
- make sure help works (btw, updated help pages: Vector Jitter qL SOP, Vector qL SOP)

**Comment by bonsak** [comment]
I'm getting both 500 and 404 errors on osx. Not sure why:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Houdini.framework/Versions/Current/Resources/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Houdini.framework/Versions/Current/Resources/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Houdini.framework/Versions/Current/Resources/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Houdini.framework/Versions/Current/Resources/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Houdini.framework/Versions/Current/Resources/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Houdini.framework/Versions/Current/Resources/houdini/python2.7libs/bookish/flaskapp.py", line 254, in show
    etag = pages.etag(spath)
  File "/Library/Frameworks/Houdini.framework/Versions/Current/Resources/houdini/python2.7libs/bookish/wikipages.py", line 233, in etag
    etag = self.store.etag(spath)
  File "/Library/Frameworks/Houdini.framework/Versions/Current/Resources/houdini/python2.7libs/bookish/stores.py", line 587, in etag
    return store.etag(path)
  File "/Library/Frameworks/Houdini.framework/Versions/Current/Resources/houdini/python2.7libs/bookish/stores.py", line 587, in etag
    return store.etag(path)
  File "/Library/Frameworks/Houdini.framework/Versions/Current/Resources/houdini/python2.7libs/bookish/stores.py", line 72, in etag
    raise NotImplementedError(self.__class__.__name__)
NotImplementedError: AssetStore
```

**Comment by johnnyquest** [comment]
Yep, I'm getting the same error on linux. This is a Houdini issue, IMHO

**Comment by johnnyquest** [comment]
A colleague tested it with the latest daily build (not sure which OS) and help was back to normal (qLib stuff worked, too). I'll close this ticket as soon as I see it working on my machine. :DDDD

**Comment by johnnyquest** [comment]
images still don't work? not just with qLib assets, but neither with Houdini ones (except the built-in ones)?

**Comment by johnnyquest** [comment]
this became #397 so i'm closing this
