### ISSUE TITLE
Name conflict with latest houdini release

### ISSUE THREAD

**Issue by samson-jerome** [qLab/qLib#800]
Hello,

I am just installing Houdin17 in our pipeline and I get several errors (does not prevent houdini from loading though) with qLib-0.2.62 package.
Do you think there might be some conflicts with houdini new attr or nodes ?

Here is the output:
```
= = = = Viewer states registration = = = =
Error: /production/data/software/packages_2.0/ext/houdini/17.0.352/platform-linux/arch-x86_64/houdini/viewer_states/sidefx_bend.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/production/data/software/packages_2.0/ext/houdini/17.0.352/platform-linux/arch-x86_64/houdini/python2.7libs/stateutils.py", line 563, in register_pystate
    hou.ui.registerViewerState( template )
  File "/production/data/software/packages_2.0/ext/houdini/17.0.352/platform-linux/arch-x86_64/houdini/python2.7libs/hou.py", line 56819, in registerViewerState
    return _hou.ui_registerViewerState(*args)
NameConflict: Name conflict was detected.
Error registering 'sidefx_bend': already registered.

Error: /production/data/software/packages_2.0/ext/houdini/17.0.352/platform-linux/arch-x86_64/houdini/viewer_states/sidefx_lop_edit.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/production/data/software/packages_2.0/ext/houdini/17.0.352/platform-linux/arch-x86_64/houdini/python2.7libs/stateutils.py", line 563, in register_pystate
    hou.ui.registerViewerState( template )
  File "/production/data/software/packages_2.0/ext/houdini/17.0.352/platform-linux/arch-x86_64/houdini/python2.7libs/hou.py", line 56819, in registerViewerState
    return _hou.ui_registerViewerState(*args)
NameConflict: Name conflict was detected.
Error registering 'sidefx_lop_edit': already registered.

Error: /production/data/software/packages_2.0/ext/houdini/17.0.352/platform-linux/arch-x86_64/houdini/viewer_states/sidefx_stroke.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/production/data/software/packages_2.0/ext/houdini/17.0.352/platform-linux/arch-x86_64/houdini/python2.7libs/stateutils.py", line 563, in register_pystate
    hou.ui.registerViewerState( template )
  File "/production/data/software/packages_2.0/ext/houdini/17.0.352/platform-linux/arch-x86_64/houdini/python2.7libs/hou.py", line 56819, in registerViewerState
    return _hou.ui_registerViewerState(*args)
NameConflict: Name conflict was detected.
Error registering 'sidefx_stroke': already registered.
```

**Comment by johnnyquest** [comment]
Hi @samson-jerome -- I don think so, this looks like an error message from the new python-scriptable view states (qLib doesn't use those). I have qLib installed since H17 was in alpha (on windows, though) and I didn't get these. Could you try without qLib installed and see if you get the same messages?

**Comment by johnnyquest** [comment]
@samson-jerome i'm closing this -- cheers
